name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish Docker Image
      uses: docker/build-push-action@v1.1.1
      with:
        username:  ${{ secrets.ReplaceWithDockerHubUserName }}
        password:  ${{ secrets.ReplaceWithDockerHubPassword }}
        repository: "com8/artemis-gbs"
        tags: "latest"
